# Generated by Django 3.0.3 on 2020-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200217_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paytm_checksum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
