# Generated by Django 3.0.3 on 2020-02-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_auto_20200224_0437'),
        ('event', '0006_auto_20200225_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.TextField(max_length=2000, verbose_name='Team Members')),
                ('extra_param_1_value', models.CharField(default='', max_length=160, verbose_name='Parameter 1')),
                ('extra_param_2_value', models.CharField(default='', max_length=160, verbose_name='Parameter 2')),
                ('extra_param_3_value', models.CharField(default='', max_length=160, verbose_name='Parameter 3')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.Profile', verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
