# Generated by Django 3.0.3 on 2020-02-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('registration', '0006_auto_20200214_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('team_event', models.BooleanField(default=False)),
                ('max_participant', models.PositiveIntegerField()),
                ('team_min_size', models.PositiveIntegerField(default=1)),
                ('team_max_size', models.PositiveIntegerField(default=1)),
                ('venue', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('registration_open', models.BooleanField(default=True)),
                ('prizes', models.TextField(max_length=300)),
                ('rules', models.TextField(max_length=1000)),
                ('extra_param_1_name', models.CharField(default='', max_length=40)),
                ('extra_param_2_name', models.CharField(default='', max_length=40)),
                ('extra_param_3_name', models.CharField(default='', max_length=40)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='base.EventCategory')),
                ('co_organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_organised_events', to='registration.Volunteer')),
                ('organiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organised_events', to='registration.Volunteer')),
            ],
        ),
    ]
