# Generated by Django 3.0.3 on 2020-02-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extra_param_1_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='extra_param_2_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='extra_param_3_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
