# Generated by Django 3.0.3 on 2020-02-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='f_p',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='First Prize'),
        ),
        migrations.AlterField(
            model_name='event',
            name='s_p',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Second Prize'),
        ),
        migrations.AlterField(
            model_name='event',
            name='t_p',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Third Prize'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vne',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Venue'),
        ),
    ]
