# Generated by Django 3.0.3 on 2020-02-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200222_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
