# Generated by Django 2.2.10 on 2020-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200222_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='rls',
            field=models.TextField(max_length=5000, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(default='', max_length=40),
        ),
    ]
