# Generated by Django 3.0.3 on 2020-02-21 14:54

from django.db import migrations, models
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='co_organiser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='extra_param_1_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='extra_param_2_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='extra_param_3_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_participant',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organiser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='prizes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_open',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_max_size',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_min_size',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_number',
            field=models.CharField(default='', max_length=13, validators=[registration.validators.validate_phone]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='f_p',
            field=models.CharField(default='', max_length=5, verbose_name='First Prize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='', upload_to='events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='rls',
            field=models.TextField(default='', max_length=1000, verbose_name='Rules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='s_p',
            field=models.CharField(default='', max_length=5, verbose_name='First Prize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='t_p',
            field=models.CharField(default='', max_length=5, verbose_name='First Prize'),
            preserve_default=False,
        ),
    ]
