# Generated by Django 3.0.3 on 2020-02-22 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_event_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_administrator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organised_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
