# Generated by Django 3.0.3 on 2020-02-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200222_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_param_1_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_param_1_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_param_2_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_param_2_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_param_3_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_param_3_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participant',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='team_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='team_max_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='team_min_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
