# Generated by Django 3.0.3 on 2020-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200226_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extra_param_2_optional',
            field=models.BooleanField(default=False, verbose_name='Extra parameter 2 is optional'),
        ),
        migrations.AlterField(
            model_name='event',
            name='extra_param_3_optional',
            field=models.BooleanField(default=False, verbose_name='Extra parameter 3 is optional'),
        ),
    ]
