# Generated by Django 3.0.3 on 2020-03-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20200226_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rule_pdf',
            field=models.FileField(blank=True, null=True, upload_to='rules_pdf', verbose_name='Rules(PDF)'),
        ),
    ]
