# Generated by Django 3.0.3 on 2020-02-05 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=13, unique=True, validators=[registration.validators.validate_phone])),
                ('profile_pic', models.ImageField(default='profilepics/default_profile_pic.jpg', upload_to='profilepics')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('college', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students', to='base.College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('fb', models.URLField(verbose_name='Facebook Profile')),
                ('linkedin', models.URLField(verbose_name='LinkedIn Profile')),
                ('insta', models.URLField(verbose_name='Instagram Profile')),
                ('is_administrator', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='registration.Profile')),
            ],
        ),
    ]
