# Generated by Django 3.0.3 on 2020-02-23 23:07

from django.db import migrations, models
import django.db.models.deletion
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_college_contact_email'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Registrant', 'verbose_name_plural': 'Registrants'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='base.College', verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[registration.validators.validate_phone], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
