# Generated by Django 3.0.3 on 2020-02-05 11:02

from django.db import migrations, models
import registration.managers


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200205_1624'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', registration.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
