# Generated by Django 3.0.3 on 2020-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='fb',
            field=models.URLField(blank=True, verbose_name='Facebook Profile'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='insta',
            field=models.URLField(blank=True, verbose_name='Instagram Profile'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='is_administrator',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profile'),
        ),
    ]
