# Generated by Django 3.0.3 on 2020-02-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200214_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='description',
        ),
    ]
