# Generated by Django 3.0.3 on 2020-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_volunteer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
